
server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PsyBrainy/microservice.git
          searchPaths: tree/main/config-data
          username: ${GIT_USER}
          password: ${GIT_PASS}
  security:
    user:
      name: root
      password: s3cr3t